%% -*- coding: utf-8 -*-
%% Automatically generated, do not edit
%% Generated by gpb_compile version 4.11.1

-ifndef('01_login').
-define('01_login', true).

-define('01_login_gpb_version', "4.11.1").

-ifndef('PT_1001_C_PB_H').
-define('PT_1001_C_PB_H', true).
-record(pt_1001_c,
        {username = []          :: iodata() | undefined, % = 1
         password = []          :: iodata() | undefined % = 2
        }).
-endif.

-ifndef('PT_1001_S_PB_H').
-define('PT_1001_S_PB_H', true).
-record(pt_1001_s,
        {ret = 0                :: non_neg_integer() | undefined % = 1, 32 bits
        }).
-endif.

-endif.
